"""added reason in appointment

Revision ID: 2b1c6a22a8b1
Revises: d1449d044920
Create Date: 2024-12-21 11:56:03.102944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1c6a22a8b1'
down_revision: Union[str, None] = 'd1449d044920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reason')
    # ### end Alembic commands ###
