"""added doctor availability

Revision ID: de595299eee7
Revises: 2b1c6a22a8b1
Create Date: 2024-12-21 12:25:26.848580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de595299eee7'
down_revision: Union[str, None] = '2b1c6a22a8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_availability',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('doctor_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_availability')
    # ### end Alembic commands ###
